### ISSUE TITLE
[1.2.0] Automation errors after upgrading to commit 9cdd347e

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#1858]
Below is a small snapshot of repeated errors since updating to commit 9cdd347e

```
2018/08/22 01:05:05 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4884 cacti_debug_backtrace)
2018/08/22 01:05:05 - ERROR PHP ERROR: Uncaught Error: Call to undefined function create_complete_graph_from_template() in /usr/share/cacti/site/lib/api_automation.php:2432 Stack trace: #0 /usr/share/cacti/site/lib/api_automation.php(2135): create_dq_graphs('2', '1', Array) #1 /usr/share/cacti/site/lib/data_query.php(159): automation_execute_data_query('2', '1') #2 /usr/share/cacti/site/poller_commands.php(104): run_data_query('2', '1') #3 {main} thrown in file: /usr/share/cacti/site/lib/api_automation.php on line: 2432
2018/08/22 01:05:05 - PCOMMAND Device[Local Net-SNMP Machine] WARNING: Recache Event Detected for Device
2018/08/22 01:05:04 - SYSTEM STATS: Time:2.4681 Method:cmd.php Processes:1 Threads:N/A Hosts:2 HostsPerProcess:2 DataSources:23 RRDsProcessed:22
2018/08/22 01:04:07 - SYSTEM THOLD STATS: Time:0.1259 Tholds:1 TotalDevices:2 DownDevices:0 NewDownDevices:0
2018/08/22 01:04:06 - THOLD_DEBUG autocreate(2) - rra_list: array ( )
2018/08/22 01:04:06 - THOLD_DEBUG autocreate(2) - rra_sql: 'SELECT id, data_template_id FROM data_local WHERE host_id = ? AND data_template_id IN (30)'
2018/08/22 01:04:06 - THOLD_DEBUG autocreate(2) - host_template_id: 4
2018/08/22 01:04:05 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4884 cacti_debug_backtrace)
2018/08/22 01:04:05 - ERROR PHP ERROR: Uncaught Error: Call to undefined function create_complete_graph_from_template() in /usr/share/cacti/site/lib/api_automation.php:2432 Stack trace: #0 /usr/share/cacti/site/lib/api_automation.php(2135): create_dq_graphs('2', '1', Array) #1 /usr/share/cacti/site/lib/data_query.php(159): automation_execute_data_query('2', '1') #2 /usr/share/cacti/site/poller_commands.php(104): run_data_query('2', '1') #3 {main} thrown in file: /usr/share/cacti/site/lib/api_automation.php on line: 2432
2018/08/22 01:04:05 - PCOMMAND Device[Local Net-SNMP Machine] WARNING: Recache Event Detected for Device
2018/08/22 01:04:04 - SYSTEM STATS: Time:2.7213 Method:cmd.php Processes:1 Threads:N/A Hosts:2 HostsPerProcess:2 DataSources:23 RRDsProcessed:22
2018/08/22 01:03:44 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php: 38 form_save)(/graphs_new.php: 124 html_graph_new_graphs)(/lib/html_graph.php: 509 host_new_graphs_save)(/graphs_new.php: 215 create_save_graph)(/lib/template.php: 1456 create_complete_graph_from_template)(/lib/template.php: 1124 create_graph_has_custom_data_properties)(/lib/template.php: 1378 sizeof)(CactiErrorHandler)(/lib/functions.php: 4841 cacti_debug_backtrace)
2018/08/22 01:03:44 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /usr/share/cacti/site/lib/template.php on line: 1378
2018/08/22 01:03:44 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 38 form_save)(/graphs_new.php: 124 html_graph_new_graphs)(/lib/html_graph.php: 509 host_new_graphs_save)(/graphs_new.php: 215 CactiErrorHandler)(/lib/functions.php: 4846 cacti_debug_backtrace)
2018/08/22 01:03:44 - ERROR PHP NOTICE: Undefined variable: values in file: /usr/share/cacti/site/graphs_new.php on line: 215
2018/08/22 01:03:41 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php: 38 form_save)(/graphs_new.php: 124 html_graph_new_graphs)(/lib/html_graph.php: 509 host_new_graphs_save)(/graphs_new.php: 215 create_save_graph)(/lib/template.php: 1436 create_complete_graph_from_template)(/lib/template.php: 1124 create_graph_has_custom_data_properties)(/lib/template.php: 1378 sizeof)(CactiErrorHandler)(/lib/functions.php: 4841 cacti_debug_backtrace)
2018/08/22 01:03:41 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /usr/share/cacti/site/lib/template.php on line: 1378
2018/08/22 01:03:41 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php: 38 form_save)(/graphs_new.php: 124 html_graph_new_graphs)(/lib/html_graph.php: 509 host_new_graphs_save)(/graphs_new.php: 215 create_save_graph)(/lib/template.php: 1436 create_complete_graph_from_template)(/lib/template.php: 1124 create_graph_has_custom_data_properties)(/lib/template.php: 1378 sizeof)(CactiErrorHandler)(/lib/functions.php: 4841 cacti_debug_backtrace)
2018/08/22 01:03:41 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /usr/share/cacti/site/lib/template.php on line: 1378
2018/08/22 01:03:40 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php: 38 form_save)(/graphs_new.php: 124 html_graph_new_graphs)(/lib/html_graph.php: 509 host_new_graphs_save)(/graphs_new.php: 215 create_save_graph)(/lib/template.php: 1436 create_complete_graph_from_template)(/lib/template.php: 1124 create_graph_has_custom_data_properties)(/lib/template.php: 1378 sizeof)(CactiErrorHandler)(/lib/functions.php: 4841 cacti_debug_backtrace)
2018/08/22 01:03:40 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /usr/share/cacti/site/lib/template.php on line: 1378
2018/08/22 01:03:40 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php: 38 form_save)(/graphs_new.php: 124 html_graph_new_graphs)(/lib/html_graph.php: 509 host_new_graphs_save)(/graphs_new.php: 215 create_save_graph)(/lib/template.php: 1436 create_complete_graph_from_template)(/lib/template.php: 1124 create_graph_has_custom_data_properties)(/lib/template.php: 1378 sizeof)(CactiErrorHandler)(/lib/functions.php: 4841 cacti_debug_backtrace)
2018/08/22 01:03:40 - ERROR PHP WARNING: sizeof(): Parameter must be an array or an object that implements Countable in file: /usr/share/cacti/site/lib/template.php on line: 1378
2018/08/22 01:03:39 - CMDPHP PHP ERROR NOTICE Backtrace: (/graphs_new.php: 38 form_save)(/graphs_new.php: 124 html_graph_new_graphs)(/lib/html_graph.php: 509 host_new_graphs_save)(/graphs_new.php: 215 CactiErrorHandler)(/lib/functions.php: 4846 cacti_debug_backtrace)
2018/08/22 01:03:39 - ERROR PHP NOTICE: Undefined variable: values in file: /usr/share/cacti/site/graphs_new.php on line: 215
```

**Comment by cigamit** [comment]
Both these issues are now resolved.

**Comment by netniV** [comment]
Confirmed.
