### ISSUE TITLE
[1.2.0 Beta 2] Reindex script throwing error related to automation..

### ISSUE THREAD

**Issue by vishnubraj** [Cacti/cacti#2145]
Please check the below strace..

```[FREE::root@cacti1a.ams2 /var/www/cacti/cli]# php -q poller_reindex_hosts.php --id=123
WARNING: Do not interrupt this script.  Reindexing can take quite some time
.PHP Fatal error:  Uncaught Error: Call to undefined function api_tree_branch_exists() in /var/www/cacti/lib/api_automation.php:2604
Stack trace:
#0 /var/www/cacti/lib/api_automation.php(2578): create_header_node('ash1', Array, Array, '0')
#1 /var/www/cacti/lib/api_automation.php(2545): create_multi_header_node('agg1.ash1', Array, Array, '0')
#2 /var/www/cacti/lib/api_automation.php(2323): create_all_header_nodes('52355', Array)
#3 /var/www/cacti/lib/api_automation.php(2080): automation_execute_graph_create_tree('52355')
#4 /var/www/cacti/lib/template.php(1305): automation_hook_graph_create_tree(Array)
#5 /var/www/cacti/lib/api_automation.php(2438): create_complete_graph_from_template('7', '123', Array, Array)
#6 /var/www/cacti/lib/api_automation.php(2141): create_dq_graphs('123', '1', Array)
#7 /var/www/cacti/lib/data_query.php(325): automation_execute_data_query('123', '1')
#8 /var/www/cacti/cli/poller_reindex_hosts.php(137): run_data_query('123', '1')
#9 {main}
  thrown in /var/www/cacti/lib/api_automation.php on line 2604
[FREE::root@cacti1a.ams2 /var/www/cacti/cli]#```

**Comment by cigamit** [comment]
Resolved.  Thanks.
