### ISSUE TITLE
i18n_themes is not properly primed in global_arrays.php

### ISSUE THREAD

**Issue by justmace** [Cacti/cacti#2191]
Hi,

There's a problem trying to upgrade the database:

```
[root@localhost cacti]# php cli/upgrade_database.php --forcever='1.1.38'
PHP Fatal error:  Uncaught Error: Call to undefined function _() in /usr/share/nginx/html/cacti/include/global_arrays.php:1718
Stack trace:
#0 /usr/share/nginx/html/cacti/include/global.php(396): include_once()
#1 /usr/share/nginx/html/cacti/include/cli_check.php(33): include('/usr/share/ngin...')
#2 /usr/share/nginx/html/cacti/cli/upgrade_database.php(26): require('/usr/share/ngin...')
#3 {main}
  thrown in /usr/share/nginx/html/cacti/include/global_arrays.php on line 1718

Fatal error: Uncaught Error: Call to undefined function _() in /usr/share/nginx/html/cacti/include/global_arrays.php:1718
Stack trace:
#0 /usr/share/nginx/html/cacti/include/global.php(396): include_once()
#1 /usr/share/nginx/html/cacti/include/cli_check.php(33): include('/usr/share/ngin...')
#2 /usr/share/nginx/html/cacti/cli/upgrade_database.php(26): require('/usr/share/ngin...')
#3 {main}
  thrown in /usr/share/nginx/html/cacti/include/global_arrays.php on line 1718
```
Checked global_arrays.php
```
$i18n_themes = array(
	_('Classic'),
	_('Modern'),
	_('Dark'),
	_('Paper-plane'),
	_('Paw'),
	_('Sunrise'),
);
```
should be 

```
$i18n_themes = array(
        __('Classic'),
        __('Modern'),
        __('Dark'),
        __('Paper-plane'),
        __('Paw'),
        __('Sunrise'),
);
```

This is the result after applying the changes

```
[root@localhost cli]# php upgrade_database.php --forcever='1.1.38'
Upgrading from v1.1.38
Upgrading from v1.1.38 (DB 1.2.0) to v1.2.0
++++++++++++++-+++++++++++++++++++++

```

**Comment by netniV** [comment]
Good catch. Thanks!

This has now been committed to the development code.
