### ISSUE TITLE
Cacti Builtin Authantication Problem

### ISSUE THREAD

**Issue by celikcihan** [Cacti/cacti#2294]
Hi,

I faced a problem when login to cacti as admin. When i try to reach console section on cacti i receive HTTP 500 error .

Here is the error log;

[Wed Jan 09 10:31:58.088335 2019] [php7:error] [pid 20850] [client x.x.x.x:26818] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function secpass_login_process(),
 0 passed in /usr/share/cacti/auth_login.php on line 160 and exactly 1 expected in /usr/share/cacti/lib/auth.php:1815\nStack trace:\n#0 /usr/share/cacti/auth_login.php(160): secpass_login_p
rocess()\n#1 /usr/share/cacti/include/auth.php(82): include('/usr/share/cact...')\n#2 /usr/share/cacti/index.php(25): include('/usr/share/cact...')\n#3 {main}\n  thrown in /usr/share/cacti/
lib/auth.php on line 1815, referer: https://x.x.x.x/cacti/index.php

**Comment by netniV** [comment]
You will need to let us know what version you are running as that line is not reflected in the latest development code.

**Comment by celikcihan** [comment]
1.1.33

**Comment by netniV** [comment]
What version of PHP?

**Comment by celikcihan** [comment]
not a new install.



User Name | Full Name | Enabled | Realm | Graph Policy | Device Policy | Template Policy | Last Login |  
-- | -- | -- | -- | -- | -- | -- | -- | --
admin | Administrator | Yes | Local | ALLOW | ALLOW | ALLOW | Friday, September 07, 2018 08:51:32



PHP 7.1.7 (cli) (built: Jul  6 2017 14:17:16) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by cigamit** [comment]
I don't see how this is happening unless the secpass plugin is somehow still installed and enabled.  Either way, there is no way, in 1.2 anyway that a string is not being passed.

**Comment by netniV** [comment]
Can you post the contents of `include/cacti_version`?

**Comment by netniV** [comment]
Also, attach a copy of your auth_login.php and lib/auth.php

**Comment by celikcihan** [comment]
[root@NWSES-Cacti include]# more cacti_version 
1.1.33

**Comment by celikcihan** [comment]
[Desktop.zip](https://github.com/Cacti/cacti/files/2748161/Desktop.zip)

**Comment by netniV** [comment]
OK, so from your files I have learned several things. 

1. I think you are running on Windows or else you ftp'd these up to windows rather than created a gzip tar on linux

2. Even after converting the PC format (\l\n) to linux format (\l), your line numbers are out of whack with the core code and tabs seem to have been converted to spaces.

That said, at first glance, these do appear to be 1.1.33 files but it is hard to tell at the moment if they have been modified at all.

**Comment by netniV** [comment]
Actually, I take that back I just realised I didn't use the -w option on the git diff.  This has shown me that something is really out of whack because you have code broken across lines that should not be broken across lines.

Also, your auth_login.php does not appear to be the 1.1.33 version as it is missing a code in places.  Did someone upgrade this recently and miss something?

**Comment by netniV** [comment]
## Broken line example 
Broken lines occur in both files and will stop the code working properly.

![image](https://user-images.githubusercontent.com/9052188/51027201-2a3eb900-1588-11e9-886f-841e5d190a2b.png)

## Wrong auth code
The following is why your failing to authenticate:

![image](https://user-images.githubusercontent.com/9052188/51027325-77bb2600-1588-11e9-83ce-5d79518394f9.png)

As a result of that last change, you are calling the wrong function

**Comment by celikcihan** [comment]
problem is solved.  cacti is upgraded to 1.2.1
