### ISSUE TITLE
When attempting to display actions that can be taken, having no actions caused error

### ISSUE THREAD

**Issue by netniV** [Cacti/cacti#2456]
**Describe the bug**
If an array is used to build up the actions to be performed, and the array is empty or the variable is null, draw_actions_dropdown() will fail and cause a backtrace.

**To Reproduce**
1. include 'lib/html.php'
2. call `draw_actions_dropdown(NULL)`
3. See error

**Expected behavior**
If there are no actions to be performed, or the variable isn't primed, draw_actions_dropdown() should simply exit without error.

**Additional context**
```
2019/02/26 12:24:28 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2019/02/26 12:24:28 - ERROR PHP ERROR: Uncaught Error: Unsupported operand types in /usr/share/cacti/develop/lib/html.php:1377 
Stack trace:
 #0 /usr/share/cacti/develop/plugins/webseer/webseer.php(430): draw_actions_dropdown(NULL)
 #1 /usr/share/cacti/develop/plugins/webseer/webseer.php(46): list_urls()
 #2 {main} thrown in file: /usr/share/cacti/develop/lib/html.php on line: 1377
```
This was caused by a variable being used globally, that wasn't properly registering as a global variable.  As such, when the edit form was being displayed, the above stack trace appeared because the global variable was thought to be empty.

**Comment by netniV** [comment]
This has now been committed to the development code.
