### ISSUE TITLE
Not seeing confirmation when creating a new graph

### ISSUE THREAD

**Issue by stormonts** [Cacti/cacti#2457]
With Cacti 1.2.1 and 1.2.2, I am seeing an error in the logs and not seeing a confirmation window when I create a new graph via Create-> New Graphs.  The graph is created, however if I place a check box in  multiple boxes to create multiple graphs, only the very first checked graph is created.

The error in the logs is:
```
2019/02/25 10:36:43 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2019/02/25 10:36:43 - ERROR PHP ERROR: Uncaught Error: Call to undefined function api_tree_branch_exists() 
in /usr/local/cacti-1.2.2/lib/api_automation.php:2683 
Stack trace:
 #0 /usr/local/cacti-1.2.2/lib/api_automation.php(2657): create_header_node('3CX-BTP-01', Array, Array, '8')
 #1 /usr/local/cacti-1.2.2/lib/api_automation.php(2624): create_multi_header_node('3CX-BTP-01', Array, Array, '8')
 #2 /usr/local/cacti-1.2.2/lib/api_automation.php(2374): create_all_header_nodes('11331', Array)
 #3 /usr/local/cacti-1.2.2/lib/api_automation.php(2131): automation_execute_graph_create_tree('11331')
 #4 /usr/local/cacti-1.2.2/lib/template.php(1319): automation_hook_graph_create_tree(Array)
 #5 /usr/local/cacti-1.2.2/lib/template.php(1619): create_complete_graph_from_template('25', 310, Array, NULL)
 #6 /usr/local/cacti-1.2.1/graphs_new.php(220): create_save_graph(310, 'sg', 1, Array, Array)
 #7 /usr/local/cacti-1.2.2/lib/html_graph.php(447): host_new_graphs_save(310)
 #8 /usr/local/cacti-1.2.1/graphs_new.php(126): html_graph_new_graphs('graphs_new.php', 310, 10, Ar 
in file: /usr/local/cacti-1.2.2/lib/api_automation.php on line: 2683
```
To reproduce, I go to Create, then New Graphs, check a box next to a graph, click Create.  It doesn't matter what type of graph I select or which device I pick.

This is running on CentOS 6.10.

**Comment by netniV** [comment]
This was supposedly rectified in issue #2145 so it's curious that you seem to have it again.

**Comment by stormonts** [comment]
Let me know what more you need from me.

**Comment by cigamit** [comment]
Found it.  The stack trace showed it all.  Thanks!
