### ISSUE TITLE
Fatal errors in /cli/ scripts

### ISSUE THREAD

**Issue by reubenfarrelly** [Cacti/cacti#266]
Just a couple as of now up to commit d547e7a6cc05c2870aaf67d2e49ed8e7c69d987d:

thunderstorm cli # php -q removespikes.php 
FATAL: You must specify an RRDfile!

PHP Fatal error:  Uncaught Error: Call to undefined function spikekill_version() in /var/www/cacti.reub.net/htdocs/cli/removespikes.php:1285
Stack trace:
#0 /var/www/cacti.reub.net/htdocs/cli/removespikes.php(1295): display_version()
#1 /var/www/cacti.reub.net/htdocs/cli/removespikes.php(349): display_help()
#2 {main}
  thrown in /var/www/cacti.reub.net/htdocs/cli/removespikes.php on line 1285
thunderstorm cli #

and an unrelated one:

thunderstorm cli # php -q analyze_database.php 

Results in this being logged:

2017-02-04 21:51:28 - CMDPHP SQL Backtrace: (/cli/analyze_database.php: 78 db_fetch_assoc)(/lib/database.php: 316 db_fetch_assoc_prepared)(/lib/database.php: 354 cacti_debug_backtrace)

**Comment by cigamit** [comment]
Can you please state the following:
1) Your OS and Version
2) Your Database and Version
3) Output of the command 'show tables in cacti' as the Cacti database account.

The reason for this is that I can not reproduce your analyze_database.php example.

**Comment by reubenfarrelly** [comment]
Sure.

System is Gentoo x86_64 (all up to date)

PHP:

thunderstorm include # php -v
PHP 7.0.15 (cli) (built: Feb  2 2017 12:40:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
thunderstorm include # 

Database is MariaDB 10.1.21

The database name is just 'cacti'.

I connected below with the details as per include/config.php - the defaults.


```
MariaDB [cacti]> show tables in cacti;
+-------------------------------------+
| Tables_in_cacti                     |
+-------------------------------------+
| aggregate_graph_templates           |
| aggregate_graph_templates_graph     |
| aggregate_graph_templates_item      |
| aggregate_graphs                    |
| aggregate_graphs_graph_item         |
| aggregate_graphs_items              |
| automation_devices                  |
| automation_graph_rule_items         |
| automation_graph_rules              |
| automation_ips                      |
| automation_match_rule_items         |
| automation_networks                 |
| automation_processes                |
| automation_snmp                     |
| automation_snmp_items               |
| automation_templates                |
| automation_tree_rule_items          |
| automation_tree_rules               |
| cdef                                |
| cdef_items                          |
| color_template_items                |
| color_templates                     |
| colors                              |
| data_input                          |
| data_input_data                     |
| data_input_fields                   |
| data_local                          |
| data_source_profiles                |
| data_source_profiles_cf             |
| data_source_profiles_rra            |
| data_source_purge_action            |
| data_source_purge_temp              |
| data_source_stats_daily             |
| data_source_stats_hourly            |
| data_source_stats_hourly_cache      |
| data_source_stats_hourly_last       |
| data_source_stats_monthly           |
| data_source_stats_weekly            |
| data_source_stats_yearly            |
| data_template                       |
| data_template_data                  |
| data_template_rrd                   |
| external_links                      |
| graph_local                         |
| graph_template_input                |
| graph_template_input_defs           |
| graph_templates                     |
| graph_templates_gprint              |
| graph_templates_graph               |
| graph_templates_item                |
| graph_tree                          |
| graph_tree_items                    |
| host                                |
| host_graph                          |
| host_snmp_cache                     |
| host_snmp_query                     |
| host_template                       |
| host_template_graph                 |
| host_template_snmp_query            |
| plugin_config                       |
| plugin_db_changes                   |
| plugin_hooks                        |
| plugin_realms                       |
| poller                              |
| poller_command                      |
| poller_data_template_field_mappings |
| poller_item                         |
| poller_output                       |
| poller_output_boost                 |
| poller_output_boost_processes       |
| poller_output_realtime              |
| poller_reindex                      |
| poller_resource_cache               |
| poller_time                         |
| reports                             |
| reports_items                       |
| sessions                            |
| settings                            |
| settings_tree                       |
| settings_user                       |
| settings_user_group                 |
| sites                               |
| snmp_query                          |
| snmp_query_graph                    |
| snmp_query_graph_rrd                |
| snmp_query_graph_rrd_sv             |
| snmp_query_graph_sv                 |
| snmpagent_cache                     |
| snmpagent_cache_notifications       |
| snmpagent_cache_textual_conventions |
| snmpagent_managers                  |
| snmpagent_managers_notifications    |
| snmpagent_mibs                      |
| snmpagent_notifications_log         |
| user_auth                           |
| user_auth_cache                     |
| user_auth_group                     |
| user_auth_group_members             |
| user_auth_group_perms               |
| user_auth_group_realm               |
| user_auth_perms                     |
| user_auth_realm                     |
| user_domains                        |
| user_domains_ldap                   |
| user_log                            |
| vdef                                |
| vdef_items                          |
| version                             |
+-------------------------------------+
108 rows in set (0.00 sec)

MariaDB [cacti]>
```

**Comment by cigamit** [comment]
Okay, run the analyze_database.php with logging set to DEVEL, and send the SQL error from the log.

**Comment by reubenfarrelly** [comment]
Ah - I made a mistake above with the database name I was connecting to, but I think I can see the problem.  The database is actually called 'cacti-upgrade' since this was an upgrade database from 0.8.8.

2017-02-05 09:35:55 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'sessions'"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Row: "SELECT value    FROM settings_user    WHERE name = ?    AND user_id = ?"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'user_domains'"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM user_domains WHERE enabled="on" ORDER BY domain_name"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Cell: "SELECT domain_id FROM user_domains WHERE defdomain=1 AND enabled="on""
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM plugin_realms ORDER BY plugin, display"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name  FROM graph_templates AS gt  INNER JOIN graph_templates_item AS gti  ON gt.id=gti.graph_template_id  INNER JOIN data_template_rrd AS dtr  ON gti.task_item_id=dtr.id  WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name  FROM plugin_config  WHERE status=1"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SELECT pc.id, ph.name, ph.file, ph.function  FROM plugin_hooks AS ph  LEFT JOIN plugin_config AS pc  ON pc.directory = ph.name  WHERE ph.status = 1 AND hook = ?  ORDER BY id ASC"
2017-02-05 09:35:55 - DBCALL DEVEL: SQL Assoc: "SHOW TABLES FROM cacti-upgrade"
2017-02-05 09:35:55 - DBCALL ERROR: SQL Assoc Failed!, Error:1064, SQL:"SHOW TABLES FROM cacti-upgrade"
2017-02-05 09:35:55 - DBCALL ERROR: SQL Assoc Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-upgrade' at line 1
2017-02-05 09:35:55 - CMDPHP SQL Backtrace: (/cli/analyze_database.php: 78 db_fetch_assoc)(/lib/database.php: 316 db_fetch_assoc_prepared)(/lib/database.php: 354 cacti_debug_backtrace)

I am thinking perhaps the script is not accounting for the fact that there is a hyphen in the database name ?

**Comment by cigamit** [comment]
This issue is resolved then.  Thanks.
