### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function api_data_source_cache_crc_update()

### ISSUE THREAD

**Issue by tersmitten** [Cacti/cacti#3981]
# Describe the bug

`add_graph_template.php` throws a PHP Fatal error about an undefined function `api_data_source_cache_crc_update`.

## To Reproduce

```sh
# echo 'SELECT `id` FROM `host` WHERE `id` IN (37);' | \
> mysql --skip-column-names cacti | \
> while read -r hostIds; do
>  hostId="${hostIds}";
>  
>  # 9.  Percona Apache Server HT
>  for hostTemplateId in 9; do
>    echo 'SELECT `graph_template_id` FROM `host_template_graph` WHERE `host_template_id` = '"${hostTemplateId}"';' | \
>    mysql --skip-column-names cacti | \
>    while read -r graphTemplateIds; do
>      graphTemplateId="${graphTemplateIds}";
> 
>      php add_graph_template.php --host-id="${hostId}" --graph-template-id="${graphTemplateId}";
>    done
>  done
> done
PHP Fatal error:  Uncaught Error: Call to undefined function api_data_source_cache_crc_update() in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php:753
Stack trace:
#0 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2261): push_out_host('37', '1755')
#1 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2121): automation_execute_graph_template('37', '35')
#2 /var/lib/ansible/cacti-server/checkouts/cacti/cli/add_graph_template.php(149): automation_hook_graph_template('37', '35')
#3 {main}
  thrown in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php on line 753
PHP Fatal error:  Uncaught Error: Call to undefined function api_data_source_cache_crc_update() in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php:753
Stack trace:
#0 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2261): push_out_host('37', '1756')
#1 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2121): automation_execute_graph_template('37', '36')
#2 /var/lib/ansible/cacti-server/checkouts/cacti/cli/add_graph_template.php(149): automation_hook_graph_template('37', '36')
#3 {main}
  thrown in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php on line 753
PHP Fatal error:  Uncaught Error: Call to undefined function api_data_source_cache_crc_update() in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php:753
Stack trace:
#0 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2261): push_out_host('37', '1757')
#1 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2121): automation_execute_graph_template('37', '37')
#2 /var/lib/ansible/cacti-server/checkouts/cacti/cli/add_graph_template.php(149): automation_hook_graph_template('37', '37')
#3 {main}
  thrown in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php on line 753
PHP Fatal error:  Uncaught Error: Call to undefined function api_data_source_cache_crc_update() in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php:753
Stack trace:
#0 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2261): push_out_host('37', '1758')
#1 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2121): automation_execute_graph_template('37', '38')
#2 /var/lib/ansible/cacti-server/checkouts/cacti/cli/add_graph_template.php(149): automation_hook_graph_template('37', '38')
#3 {main}
  thrown in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php on line 753
PHP Fatal error:  Uncaught Error: Call to undefined function api_data_source_cache_crc_update() in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php:753
Stack trace:
#0 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2261): push_out_host('37', '1759')
#1 /var/lib/ansible/cacti-server/checkouts/cacti/lib/api_automation.php(2121): automation_execute_graph_template('37', '39')
#2 /var/lib/ansible/cacti-server/checkouts/cacti/cli/add_graph_template.php(149): automation_hook_graph_template('37', '39')
#3 {main}
  thrown in /var/lib/ansible/cacti-server/checkouts/cacti/lib/utility.php on line 753
```

## Expected behavior

PHP Fatal error thrown

## Additional context

**OS**: Ubuntu 16.04
**PHP version**: PHP 7.2
**MySQL version**: Percona Server 5.7
**Cacti version**: 1.2.16

**Comment by TheWitness** [comment]
Ugh.

**Comment by tersmitten** [comment]
Maybe a missing import of:

```php
<?php
include_once($config['library_path'] . '/poller.php'); // Also needed?
include_once($config['library_path'] . '/api_data_source.php');
```
