### ISSUE TITLE
You just broke the graphs :) Feel free to rename

### ISSUE THREAD

**Issue by jdcoats** [Cacti/cacti#4037]
```

2021-01-06 13:15:10 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
--
2021-01-06 13:15:10 - ERROR PHP : Uncaught Error: Call to undefined function get_request_var() in /var/www/localhost/htdocs/cacti/lib/functions.php:3097 Stack trace: #0 /var/www/localhost/htdocs/cacti/include/global.php(476): sanitize_uri('https://syslog0...') #1 /var/www/localhost/htdocs/cacti/include/auth.php(28): require_once('/var/www/localh...') #2 /var/www/localhost/htdocs/cacti/clog.php(27): include('/var/www/localh...') #3 {main} thrown in file: /var/www/localhost/htdocs/cacti/lib/functions.php on line: 3097
2021-01-06 13:15:10 - CMDPHP PHP ERROR NOTICE Backtrace: (CactiShutdownHandler(), /lib/functions.php[4633]:CactiErrorHandler())
2021-01-06 13:15:10 - ERROR PHP : Trying to access array offset on value of type null in file: /var/www/localhost/htdocs/cacti/lib/functions.php on line: 4633
2021-01-06 13:14:44 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2021-01-06 13:14:44 - ERROR PHP : Uncaught Error: Call to undefined function get_request_var() in /var/www/localhost/htdocs/cacti/lib/functions.php:3097 Stack trace: #0 /var/www/localhost/htdocs/cacti/include/global.php(476): sanitize_uri('https://syslog0...') #1 /var/www/localhost/htdocs/cacti/include/auth.php(28): require_once('/var/www/localh...') #2 /var/www/localhost/htdocs/cacti/graph_view.php(27): include('/var/www/localh...') #3 {main} thrown in file: /var/www/localhost/htdocs/cacti/lib/functions.php on line: 3097
2021-01-06 13:14:44 - CMDPHP PHP ERROR NOTICE Backtrace: (CactiShutdownHandler(), /lib/functions.php[4633]:CactiErrorHandler())
2021-01-06 13:14:44 - ERROR PHP : Trying to access array offset on value of type null in file: /var/www/localhost/htdocs/cacti/lib/functions.php on line: 4633


```

**Comment by TheWitness** [comment]
Great.

**Comment by TheWitness** [comment]
Try again...

**Comment by TheWitness** [comment]
Just going to close in shame (of myself)
