### ISSUE TITLE
[1.2.x Branch ] poller_boost.php throws error

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4090]
I was just testing the new boost multi process code and found the following errors 

```
root@cacti-1:/var/www/html/cacti# php poller_boost.php --force --debug
DEBUG: Checking if Boost is ready to run.
DEBUG: Last Runtime was 2021-01-23 14:41:05 (1611434465).
DEBUG: Next Runtime is 1969-12-31 18:00:00 ().
DEBUG: Records Found:2115, Max Threshold:1000000.
DEBUG: Time to Run Boost, Force Run is true!
DEBUG: Parallel Process Setup Begins.
PHP Fatal error:  Uncaught Error: Call to undefined function boost_get_arch_table_names() in /var/www/html/cacti/poller_boost.php:301
Stack trace:
#0 /var/www/html/cacti/poller_boost.php(140): boost_prepare_process_table()
#1 {main}
  thrown in /var/www/html/cacti/poller_boost.php on line 301
root@cacti-1:/var/www/html/cacti# ^C
```

**Comment by bmfmancini** [comment]
The following errors show up when Cacti tries to run Boost 

```
2021-01-23 14:48:39 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2021-01-23 14:48:39 - ERROR PHP ERROR: Uncaught Error: Call to  undefined function boost_get_arch_table_names() in  /var/www/html/cacti/poller_boost.php:301 Stack trace: #0  /var/www/html/cacti/poller_boost.php(140): boost_prepare_process_table()  #1 {main} thrown in file: /var/www/html/cacti/poller_boost.php on line:  30
```

**Comment by TheWitness** [comment]
Oh, that weird.  Thanks for testing.

**Comment by TheWitness** [comment]
You need to update lib/boost.php to the latest release.

**Comment by bmfmancini** [comment]
Opps my bad I downloaded both files but did not copy it to the lib folder
