### ISSUE TITLE
Stuck on Creating Graphs for Default Device Cacti 1.2.17

### ISSUE THREAD

**Issue by Magnum5911** [Cacti/cacti#4358]
Hello

I am using Windows server 2016 to install Cacti V1.12.17 but stuck on Creating Graphs for Default Device few hours, may I know any solution to fix it?

Dump screen as attachment.
![Capture](https://user-images.githubusercontent.com/60601259/126903054-f349afc1-9dc1-4b34-826a-9eb656152656.JPG)

> 2021-07-23 17:27:26 - ERROR PHP ERROR: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cacti\poller.php:340 Stack trace: #0 C:\xampp\htdocs\cacti\poller.php(340): round('never', 2) #1 {main} thrown in file: C:\xampp\htdocs\cacti\poller.php on line: 340
2021-07-23 17:27:26 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2021-07-23 17:30:46 - ERROR PHP ERROR: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cacti\poller.php:340 Stack trace: #0 C:\xampp\htdocs\cacti\poller.php(340): round('never', 2) #1 {main} thrown in file: C:\xampp\htdocs\cacti\poller.php on line: 340
2021-07-23 17:30:46 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2021-07-23 17:35:45 - ERROR PHP ERROR: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cacti\poller.php:340 Stack trace: #0 C:\xampp\htdocs\cacti\poller.php(340): round('never', 2) #1 {main} thrown in file: C:\xampp\htdocs\cacti\poller.php on line: 340
2021-07-23 17:35:45 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2021-07-23 17:40:46 - ERROR PHP ERROR: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cacti\poller.php:340 Stack trace: #0 C:\xampp\htdocs\cacti\poller.php(340): round('never', 2) #1 {main} thrown in file: C:\xampp\htdocs\cacti\poller.php on line: 340
2021-07-23 17:40:46 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2021-07-23 17:45:46 - ERROR PHP ERROR: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cacti\poller.php:340 Stack trace: #0 C:\xampp\htdocs\cacti\poller.php(340): round('never', 2) #1 {main} thrown in file: C:\xampp\htdocs\cacti\poller.php on line: 340
2021-07-23 17:45:46 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2021-07-23 17:50:46 - ERROR PHP ERROR: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cacti\poller.php:340 Stack trace: #0 C:\xampp\htdocs\cacti\poller.php(340): round('never', 2) #1 {main} thrown in file: C:\xampp\htdocs\cacti\poller.php on line: 340
2021-07-23 17:50:46 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())

Thanks,

**Comment by netniV** [comment]
I believe this was already logged and patched.
