### ISSUE TITLE
incomplete polling 

### ISSUE THREAD

**Issue by anaskhatib** [Cacti/cacti#5000]
Hello, 
We have issues with CACTI, the polling is not complete, note that we tried to increase the number of processes but still its one 
process, also there is error as shown in below logs: 
note that, some devices status is : unknown

<html>
<body>

2022-11-12 00:55:02 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
--
2022-11-12 00:55:02 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149
2022-11-12 00:55:00 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:54:59 - SYSTEM STATS: Time:299.3607 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2696
2022-11-12 00:54:59 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:54:59 - POLLER: Poller[Main Poller] PID[346967] Maximum runtime of 298 seconds exceeded. Exiting.
2022-11-12 00:50:00 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:50:00 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:50:00 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149
2022-11-12 00:50:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:50:00 - POLLER: Poller[Main Poller] PID[346967] WARNING: There are 1 processes detected as overrunning a polling cycle, please investigate
2022-11-12 00:49:59 - SYSTEM STATS: Time:299.3742 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2696
2022-11-12 00:49:59 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:49:59 - POLLER: Poller[Main Poller] PID[344431] Maximum runtime of 298 seconds exceeded. Exiting.
2022-11-12 00:45:02 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:45:00 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:45:00 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149
2022-11-12 00:45:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:45:00 - POLLER: Poller[Main Poller] PID[344431] WARNING: There are 1 processes detected as overrunning a polling cycle, please investigate
2022-11-12 00:45:00 - SYSTEM STATS: Time:298.3603 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2694
2022-11-12 00:45:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:45:00 - POLLER: Poller[Main Poller] PID[341039] Maximum runtime of 298 seconds exceeded. Exiting.
2022-11-12 00:40:02 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:40:02 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149
2022-11-12 00:40:01 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:40:01 - POLLER: Poller[Main Poller] PID[341039] WARNING: Poller Output Table not Empty. Issues: 1, DS[DAM1_PE - Traffic - smartgroup2.1519] Graphs[DAM1_PE - Traffic - smartgroup2.1519]
2022-11-12 00:40:00 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:39:59 - SYSTEM STATS: Time:299.3559 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2697
2022-11-12 00:39:59 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:39:59 - POLLER: Poller[Main Poller] PID[338481] Maximum runtime of 298 seconds exceeded. Exiting.
2022-11-12 00:35:01 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:35:00 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:35:00 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149

</body>
</html>2022-11-12 00:55:02 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:55:02 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149
2022-11-12 00:55:00 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:54:59 - SYSTEM STATS: Time:299.3607 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2696
2022-11-12 00:54:59 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:54:59 - POLLER: Poller[[Main Poller](http://biz.go.com.sa/cacti/pollers.php?action=edit&id=1)] PID[346967] Maximum runtime of 298 seconds exceeded. Exiting.
2022-11-12 00:50:00 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:50:00 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:50:00 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149
2022-11-12 00:50:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:50:00 - POLLER: Poller[[Main Poller](http://biz.go.com.sa/cacti/pollers.php?action=edit&id=1)] PID[346967] WARNING: There are 1 processes detected as overrunning a polling cycle, please investigate
2022-11-12 00:49:59 - SYSTEM STATS: Time:299.3742 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2696
2022-11-12 00:49:59 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:49:59 - POLLER: Poller[[Main Poller](http://biz.go.com.sa/cacti/pollers.php?action=edit&id=1)] PID[344431] Maximum runtime of 298 seconds exceeded. Exiting.
2022-11-12 00:45:02 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:45:00 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:45:00 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149
2022-11-12 00:45:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:45:00 - POLLER: Poller[[Main Poller](http://biz.go.com.sa/cacti/pollers.php?action=edit&id=1)] PID[344431] WARNING: There are 1 processes detected as overrunning a polling cycle, please investigate
2022-11-12 00:45:00 - SYSTEM STATS: Time:298.3603 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2694
2022-11-12 00:45:00 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:45:00 - POLLER: Poller[[Main Poller](http://biz.go.com.sa/cacti/pollers.php?action=edit&id=1)] PID[341039] Maximum runtime of 298 seconds exceeded. Exiting.
2022-11-12 00:40:02 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:40:02 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149
2022-11-12 00:40:01 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:40:01 - POLLER: Poller[[Main Poller](http://biz.go.com.sa/cacti/pollers.php?action=edit&id=1)] PID[341039] WARNING: Poller Output Table not Empty. Issues: 1, DS[[DAM1_PE - Traffic - smartgroup2.1519](http://biz.go.com.sa/cacti/data_sources.php?action=ds_edit&id=2296)] Graphs[[DAM1_PE - Traffic - smartgroup2.1519](http://biz.go.com.sa/cacti/graph_view.php?page=1&style=selective&action=preview&graph_add=2290)]
2022-11-12 00:40:00 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:39:59 - SYSTEM STATS: Time:299.3559 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2697
2022-11-12 00:39:59 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2022-11-12 00:39:59 - POLLER: Poller[[Main Poller](http://biz.go.com.sa/cacti/pollers.php?action=edit&id=1)] PID[338481] Maximum runtime of 298 seconds exceeded. Exiting.
2022-11-12 00:35:01 - CMDPHP WARNING: cmd.php poller has run over its polling interval and therefore is ending
2022-11-12 00:35:00 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-11-12 00:35:00 - ERROR PHP ERROR: Uncaught TypeError: closedir(): Argument #1 ($dir_handle) must be of type resource or null, bool given in /usr/share/cacti/scripts/cacti_user_stats.php:149 Stack trace: #0 /usr/share/cacti/scripts/cacti_user_stats.php(149): closedir() #1 {main} thrown in file: /usr/share/cacti/scripts/cacti_user_stats.php on line: 149

Date | Sat, 12 Nov 2022 01:04:20 +0300
Cacti Version | 1.2.22
NET-SNMP Version | NET-SNMP version: 5.9.1
RRDtool Version Configured | 1.7.2+
RRDtool Version Found | 1.7.2
Devices | 35
Graphs | 4,055
Data Sources | Script/Command: 40Script Server: 72SNMP Query: 3,899SNMP Get: 7Total: 4,018

Interval | 300
Type | cmd.php
Items | Action[0]: 7,798Action[1]: 39Action[2]: 70Total: 7,907
Concurrent Processes | Name: Main Poller, Procs: 1
Max Threads | Name: Main Poller, Threads: 1
PHP Servers | 15
Minimum Connections: | Current: 151, Min Required: 116Assumes 100 spare connections for Web page users and other various connections.The minimum required can vary greatly if there is heavy user Graph viewing activity.Each browser tab can use upto 10 connections depending on the browser.
Script Timeout | 25
Max OID | 10
Last Run Statistics | Time:298.3391 Method:cmd.php Processes:1 Threads:1 Hosts:34 HostsPerProcess:34 DataSources:7907 RRDsProcessed:2696

MemTotal | 30.36 G
MemFree | 13.11 G
MemAvailable | 27.87 G
Buffers | 1.16 G
Cached | 13.35 G
Active | 11.62 G
Inactive | 4.52 G
SwapTotal | 1.95 G
SwapFree | 1.95 G

PHP Version | 8.1.2-1ubuntu2.8
PHP OS | Linux
PHP uname | Linux bizcacti-OptiPlex-7090 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64
PHP SNMP | Installed. Note: If you are planning on using SNMPv3, you must remove php-snmp and use the Net-SNMP toolset.
max_execution_time | 60
memory_limit | 400M

</body>
</html>

**Comment by TheWitness** [comment]
Use spine or increase your concurrent processes.  Concurrent processes are set in `Console > Data Collection > Data Collectors`
