### ISSUE TITLE
Cacti 1.2.22 - RRDfile is not created / updated, possibly due to Spine bug

### ISSUE THREAD

**Issue by janmaris** [Cacti/cacti#5011]
Hi, the cactid service is running fine, but the RRD files are not created or updated, possibly due to a Segmentation Violation issue with Spine (currently using version 1.2.23).

debugging output is as follows:

```
root@server:/usr/local/spine/bin# gdb spine
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from spine...
(gdb) run -R -C /usr/local/spine/etc/spine.conf.dist
Starting program: /usr/local/spine/bin/spine -R -C /usr/local/spine/etc/spine.conf.dist
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
SPINE: Using spine config file [/usr/local/spine/etc/spine.conf.dist]

Program received signal SIGSEGV, Segmentation fault.
0x000055568946f030 in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1255
1255            va_start(args, format);
(gdb) where
#0  0x000055568946f030 in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1255
#1  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
#2  0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
#3  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
#4  0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
#5  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
#6  0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
#7  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
#8  0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
#9  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
#10 0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
#11 0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
#12 0x000055568946f34a in spine_log (format=format@entry=0x55568947f81b "DEVDBG: SQL:%s") at util.c:1316
#13 0x000055568946d988 in db_query (mysql=mysql@entry=0x7ffdad89d030, type=type@entry=0, query=query@entry=0x7ffdad89c8e0 "SELECT value FROM settings WHERE name = 'path_webroot'") at sql.c:156
#14 0x000055568946e854 in getsetting (psql=psql@entry=0x7ffdad89d030, setting=setting@entry=0x5556894826e7 "path_webroot", mode=0) at util.c:100
#15 0x0000555689471919 in read_config_options () at util.c:385
#16 0x000055568946bf88 in main (argc=<optimized out>, argv=<optimized out>) at spine.c:492
(gdb) list
1250            char flogmessage[LOGSIZE];     /* Formatted Log Message */
1251            char stdoutmessage[LRG_LOGSIZE];   /* Message for stdout */
1252
1253            double cur_time;
1254
1255            va_start(args, format);
1256            vsnprintf(ulogmessage, LOGSIZE - 1, format, args);
1257            va_end(args);
1258
1259            /* default for "console" messages to go to stdout */
(gdb)
```

Thanks for any further help or suggestions to get this resolved.
Jan

**Comment by TheWitness** [comment]
I think that is a at developer debug level.  What is your OS and version?

**Comment by TheWitness** [comment]
Are you sure you are running 1.2.23 and not develop?  Try running the 1.2.x branch instead.  Line numbers are not adding up.  And try not to run in Developer Debug.
