### ISSUE TITLE
1.3.0 - QA - Unable to add SNMP string to default snmp option set in automation

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5032]
When trying to add a SNMP string in the default snmp option page 
Click the + to add the snmp string cacti will error out with the last action was not expected 
the following errors are logged

```


2022-12-04 00:02:28 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2022-12-04 00:02:28 - ERROR PHP ERROR: Uncaught TypeError:  get_sequence(): Argument #1 ($id) must be of type ?int, string given,  called in /var/www/html/cacti/automation_snmp.php on line 441 and  defined in /var/www/html/cacti/lib/functions.php:3516 Stack trace: #0  /var/www/html/cacti/automation_snmp.php(441): get_sequence() #1  /var/www/html/cacti/automation_snmp.php(82): automation_snmp_item_edit()  #2 {main} thrown in file: /var/www/html/cacti/lib/functions.php on  line: 3516
```

**Comment by TheWitness** [comment]
Should be fixed now.

**Comment by bmfmancini** [comment]
Tested working fine now
