### ISSUE TITLE
1.3.0 - QA Errors modifying graph template 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5081]
When modifying a graph template 

Add an item and click save shutdown handler kicks in with the following errors

```
2022-12-12 14:32:31 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2022-12-12 14:32:31 - ERROR PHP ERROR: Uncaught TypeError:  get_sequence(): Argument #1 ($id) must be of type ?int, string given,  called in /var/www/html/cacti/graph_templates_items.php on line 195 and  defined in /var/www/html/cacti/lib/functions.php:3567 Stack trace: #0  /var/www/html/cacti/graph_templates_items.php(195): get_sequence() #1  /var/www/html/cacti/graph_templates_items.php(35): form_save() #2 {main}  thrown in file: /var/www/html/cacti/lib/functions.php on line: 3567
```

**Comment by netniV** [comment]
Your commit shouldn't have any affect anyway. I believe 
`sequence` is set to zero higher up.

**Comment by bmfmancini** [comment]
tested all good now !
