### ISSUE TITLE
Remote Data Collector Recovery Fails

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5101]
when a remote poller fails the recovery fails with the below errors occour and the poller does not recover

```
2022-12-18 08:33:05 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2022-12-18 08:33:05 - SYSTEM MAINT STATS: Time:0.02
2022-12-18 08:34:04 - SYSTEM STATS: Time:2.2168 Method:cmd.php Processes:1 Threads:1 Hosts:10 HostsPerProcess:10 DataSources:8 RRDsProcessed:0
2022-12-18 08:34:04 - POLLER: Poller[2] PID[3100] NOTE: Remote Data Collection to force processing of boost records.
2022-12-18 08:34:05 - POLLER: Poller[2] PID[3159] RECOVERY: No pid exists, starting recovery process (PID=3159)!
2022-12-18 08:34:05 - CMDPHP ERROR: A DB Row Failed!, Error: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
2022-12-18 08:34:05 - CMDPHP SQL Backtrace:  (/poller_recovery.php[196]:poller_push_reindex_data_to_poller(), /lib/poller.php[1872]:db_fetch_assoc_prepared(), /lib/database.php[701]:db_execute_prepared())
2022-12-18 08:34:05 - ERROR PHP ERROR: Uncaught TypeError: array_rekey(): Argument #1 ($array) must be of type array, bool given, called in /var/www/html/cacti/lib/poller.php on line 1873 and defined in /var/www/html/cacti/lib/functions.php:1247 Stack trace: #0 /var/www/html/cacti/lib/poller.php(1873): array_rekey() #1 /var/www/html/cacti/poller_recovery.php(196): poller_push_reindex_data_to_poller() #2 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 1247
2022-12-18 08:34:05 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2022-12-18 08:34:05 - SYSTEM MAINT STATS: Time:0.02



2022-12-18 08:36:05 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2022-12-18 08:36:05 - ERROR PHP ERROR: Uncaught TypeError:  array_rekey(): Argument #1 ($array) must be of type array, bool given,  called in /var/www/html/cacti/lib/poller.php on line 1873 and defined in  /var/www/html/cacti/lib/functions.php:1247 Stack trace: #0  /var/www/html/cacti/lib/poller.php(1873): array_rekey() #1  /var/www/html/cacti/poller_recovery.php(196):  poller_push_reindex_data_to_poller() #2 {main} thrown in file:  /var/www/html/cacti/lib/functions.php on line: 1247
2022-12-18 08:36:05 - CMDPHP SQL Backtrace:   (/poller_recovery.php[196]:poller_push_reindex_data_to_poller(),  /lib/poller.php[1872]:db_fetch_assoc_prepared(),  /lib/database.php[701]:db_execute_prepared())
2022-12-18 08:36:05 - CMDPHP ERROR: A DB Row Failed!, Error:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number:  number of bound variables does not match number of tokens
2022-12-18 08:36:05 - POLLER: Poller[remote] PID[3417] RECOVERY: No pid exists, starting recovery process (PID=3417)!
2022-12-18 08:36:05 - SYSTEM MAINT STATS: Time:0.02
2022-12-18 08:36:05 - POLLER: Poller[remote] PID[3361] NOTE: Remote Data Collection to force processing of boost records.
2022-12-18 08:36:05 - SYSTEM STATS: Time:2.2043 Method:cmd.php Processes:1 Thre

2022-12-18 08:36:05 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2022-12-18 08:36:05 - ERROR PHP ERROR: Uncaught TypeError: array_rekey(): Argument #1 ($array) must be of type array, bool given, called in /var/www/html/cacti/lib/poller.php on line 1873 and defined in /var/www/html/cacti/lib/functions.php:1247 Stack trace: #0 /var/www/html/cacti/lib/poller.php(1873): array_rekey() #1 /var/www/html/cacti/poller_recovery.php(196): poller_push_reindex_data_to_poller() #2 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 1247
2022-12-18 08:36:05 - CMDPHP SQL Backtrace: (/poller_recovery.php[196]:poller_push_reindex_data_to_poller(), /lib/poller.php[1872]:db_fetch_assoc_prepared(), /lib/database.php[701]:db_execute_prepared())
2022-12-18 08:36:05 - CMDPHP ERROR: A DB Row Failed!, Error: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
2022-12-18 08:36:05 - POLLER: Poller[[remote](http://192.168.1.202/cacti/pollers.php?action=edit&id=2)] PID[3417] RECOVERY: No pid exists, starting recovery process (PID=3417)!
2022-12-18 08:36:05 - SYSTEM MAINT STATS: Time:0.02
2022-12-18 08:36:05 - POLLER: Poller[[remote](http://192.168.1.202/cacti/pollers.php?action=edit&id=2)] PID[3361] NOTE: Remote Data Collection to force processing of boost records.
2022-12-18 08:36:05 - SYSTEM STATS: Time:2.2043 Method:cmd.php Processes:1 Thre


```

**Comment by bmfmancini** [comment]
Work around truncate poller_output_boost poller recovers

**Comment by bmfmancini** [comment]
```
[root@localhost cacti]# php poller_recovery.php --verbose
PHP Fatal error:  Uncaught TypeError: array_rekey(): Argument #1 ($array) must be of type array, bool given, called in /var/www/html/cacti/lib/poller.php on line 1876 and defined in /var/www/html/cacti/lib/functions.php:1247
Stack trace:
#0 /var/www/html/cacti/lib/poller.php(1876): array_rekey()
#1 /var/www/html/cacti/poller_recovery.php(196): poller_push_reindex_data_to_poller()
#2 {main}
  thrown in /var/www/html/cacti/lib/functions.php on line 1247
[root@localhost cacti]# ^C
```

**Comment by TheWitness** [comment]
Pretty sure this affects 1.2.23 as well.  Publishing a patch there first, then 1.3.0.

**Comment by TheWitness** [comment]
I've published an update.  Please redo the test as you did before.

**Comment by TheWitness** [comment]
I've now tested this and corrected a minor issue.  Please continue testing from your point of view.  Thanks!

**Comment by TheWitness** [comment]
@bmfmancini, keeping this open till you get a chance to retest.  I've confirmed on my side that it recovers just fine now.

**Comment by bmfmancini** [comment]
@TheWitness  

Now seeing the following errors when main poller fails 
```
2022-12-18 16:50:08 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2022-12-18 16:50:08 - ERROR PHP ERROR: Uncaught TypeError:  read_default_user_setting(): Return value must be of type mixed, none  returned in /var/www/html/cacti/lib/functions.php:319 Stack trace: #0  /var/www/html/cacti/lib/functions.php(399): read_default_user_setting()  #1 /var/www/html/cacti/include/global_session.php(103):  read_user_setting() #2 /var/www/html/cacti/lib/html.php(2830):  include_once('...') #3 /var/www/html/cacti/auth_login.php(377):  html_auth_footer() #4 /var/www/html/cacti/include/auth.php(167):  require_once('...') #5 /var/www/html/cacti/index.php(25): include('...')  #6 {main} thrown in file: /var/www/html/cacti/lib/functions.php on  line: 319
2022-12-18 16:50:08 - CMDPHP Connection: offline, Previous Mode: notset
2022-12-18 16:49:44 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2022-12-18 16:49:44 - ERROR PHP ERROR: Uncaught TypeError:  read_default_user_setting(): Return value must be of type mixed, none  returned in /var/www/html/cacti/lib/functions.php:319 Stack trace: #0  /var/www/html/cacti/lib/functions.php(399): read_default_user_setting()  #1 /var/www/html/cacti/include/global_session.php(103):  read_user_setting() #2 /var/www/html/cacti/lib/html.php(2830):  include_once('...') #3 /var/www/html/cacti/logout.php(62):  html_auth_footer() #4 {main} thrown in file:  /var/www/html/cacti/lib/functions.php on line: 319

```

confirmed recovery works

**Comment by bmfmancini** [comment]
confirmed all good
