### ISSUE TITLE
1.3 -QA errors when logging into cacti

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#5106]
after pulling the change commits I am seeing the following when  logging into the cacti gui

```


2022-12-18 16:38:16 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
--
2022-12-18 16:38:16 - ERROR PHP ERROR: Uncaught TypeError:  read_default_user_setting(): Return value must be of type mixed, none  returned in /var/www/html/cacti/lib/functions.php:319 Stack trace: #0  /var/www/html/cacti/lib/functions.php(399): read_default_user_setting()  #1 /var/www/html/cacti/include/global_session.php(103):  read_user_setting() #2 /var/www/html/cacti/lib/html.php(2830):  include_once('...') #3 /var/www/html/cacti/auth_login.php(377):  html_auth_footer() #4 /var/www/html/cacti/include/auth.php(167):  require_once('...') #5 /var/www/html/cacti/index.php(25): include('...')  #6 {main} thrown in file: /var/www/html/cacti/lib/functions.php on  line: 319


```

**Comment by TheWitness** [comment]
Fixed here: https://github.com/Cacti/cacti/commit/b435cd54eeec90da53d3fe9d4c741a114b9632ca

**Comment by bmfmancini** [comment]
confirmed all good
