### ISSUE TITLE
1.3.0 - cannot login after upgrade (from other PC)

### ISSUE THREAD

**Issue by xmacan** [Cacti/cacti#5108]
I did upgrade to develop branch and everything works fine. I'm unable to login from another PCs after upgrade. I got:

2022-12-19 09:08:57 - ERROR PHP ERROR: Uncaught TypeError: read_default_user_setting(): Return value must be of type mixed, none returned in /usr/local/share/cacti_develop/lib/functions.php:319 Stack trace: #0 /usr/local/share/cacti_develop/lib/functions.php(399): read_default_user_setting('user_auto_logou...') #1 /usr/local/share/cacti_develop/include/global_session.php(103): read_user_setting('user_auto_logou...') #2 /usr/local/share/cacti_develop/lib/html.php(2808): include_once('/usr/local/shar...') #3 /usr/local/share/cacti_develop/auth_login.php(377): html_auth_footer('login', '', '\n\t<script>\n\t\tva...') #4 /usr/local/share/cacti_develop/include/auth.php(167): require_once('/usr/local/shar...') #5 /usr/local/share/cacti_develop/index.php(25): include('/usr/local/shar...') #6 {main} thrown in file: /usr/local/share/cacti_develop/lib/functions.php on line: 319

**Comment by xmacan** [comment]
It is bigger problem. User settings doesn't exist, the same problem in create graph graphs_new.php:
Fatal error: Uncaught TypeError: read_default_user_setting(): Return value must be of type mixed, none returned in /usr/local/share/cacti_develop/lib/functions.php:320 Stack trace: #0 /usr/local/share/cacti_develop/lib/functions.php(400): read_default_user_setting('default_sgg_4') #1 /usr/local/share/cacti_develop/graphs_new.php(109): read_user_setting('default_sgg_4') #2 /usr/local/share/cacti_develop/graphs_new.php(950): store_get_selected_dq_index(4) #3 /usr/local/share/cacti_develop/graphs_new.php(68): graphs() #4 {main} thrown in /usr/local/share/cacti_develop/lib/functions.php on line 320

**Comment by netniV** [comment]
Can you reverify this, as there have been some changes?

**Comment by xmacan** [comment]
Login works fine now, create graph too. 

New problem - button logout doesn't work. It returns me back to console

**Comment by TheWitness** [comment]
Logout is my bad.  Try to fix it today.
