### ISSUE TITLE
Error adding template to device

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5548]
# Describe the bug

When adding a graph template to a device, a 500 error is shown.   However, the template is added.

## To Reproduce

1 - Go to Devices
2 - pick a device (click device description)
3 - Add graph template
4 - See error

## Expected behavior

Graph template should be added, without error.

## Screenshots
![image](https://github.com/Cacti/cacti/assets/2725066/3d829a2f-c22f-407a-a450-70bc1f0ca45d)

Cacti Log:

```
2023-11-02 09:16:01 - PHP ERROR Backtrace: (CactiShutdownHandler())
2023-11-02 09:16:01 - ERROR PHP ERROR: Uncaught TypeError: array_rekey(): Argument #1 ($array) must be of type array, bool given, called in /var/www/html/cacti/lib/utility.php on line 1948 and defined in /var/www/html/cacti/lib/functions.php:1315 Stack trace: #0 /var/www/html/cacti/lib/utility.php(1948): array_rekey() #1 /var/www/html/cacti/host.php(695): object_cache_get_totals() #2 /var/www/html/cacti/host.php(78): host_add_gt() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 1315
2023-11-02 09:16:01 - SQL Backtrace: (/host.php[78]:host_add_gt(), /host.php[695]:object_cache_get_totals(), /lib/utility.php[1946]:db_fetch_assoc(), /lib/database.php[810]:db_fetch_assoc_prepared(), /lib/database.php[834]:db_execute_prepared())
2023-11-02 09:16:01 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY host_id' at line 1
2023-11-02 09:16:01 - PHP ERROR Backtrace: (/host.php[78]:host_add_gt(), /host.php[695]:object_cache_get_totals(), /lib/utility.php[1929]:explode(), CactiErrorHandler())
2023-11-02 09:16:01 - ERROR PHP DEPRECATED: explode(): Passing null to parameter #2 ($string) of type string is deprecated in file: /var/www/html/cacti/lib/utility.php on line: 1929
2023-11-02 09:16:01 - PHP ERROR WARNING Backtrace: (/host.php[78]:host_add_gt(), /host.php[695]:CactiErrorHandler())
2023-11-02 09:16:01 - ERROR PHP WARNING: Trying to access array offset on value of type null in file: /var/www/html/cacti/host.php on line: 695
2023-11-02 09:16:01 - PHP ERROR WARNING Backtrace: (/host.php[78]:host_add_gt(), /host.php[695]:CactiErrorHandler())
2023-11-02 09:16:01 - ERROR PHP WARNING: Undefined variable $host in file: /var/www/html/cacti/host.php on line: 695

```

Linux nmsdev 5.15.0-87-generic https://github.com/Cacti/cacti/issues/97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

mysql-server/jammy-updates,jammy-security,now 8.0.34-0ubuntu0.22.04.1 all [installed]
php8.1/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 all [installed,automatic]
php8.1-cli/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-common/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-gd/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-gmp/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-intl/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-ldap/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-mbstring/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-mysql/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-opcache/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-readline/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-snmp/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed,automatic]
php8.1-xml/jammy-updates,jammy-security,now 8.1.2-1ubuntu2.14 amd64 [installed]

**Comment by TheWitness** [comment]
What version of Cati?  Installed from source or package/rpm?

**Comment by dallenk** [comment]
Hi, installed from source, most current pull from git

**Comment by jab60** [comment]
FYI 
Reproduced with [ 1.3.0 - Dev dc2fdf8f @ 2023-11-03 16:46 ]
Log error
2023-11-03 17:33:04 - ERROR PHP WARNING: Undefined variable $host in file: /var/www/html/cacti/host.php on line: 695

Replaced as below to fix
```
/*              object_cache_get_totals('device_state', $host['id']);*/
                object_cache_get_totals('device_state', get_request_var('host_id'));
```

**Comment by TheWitness** [comment]
That commit did not include any of those changes.  Let me take a peak.

**Comment by TheWitness** [comment]
This is resolved now.  Thanks for reporting!
