### ISSUE TITLE
Cacti 1.3.0 - Dev 18f183ba - Errors on create Apache Graphs

### ISSUE THREAD

**Issue by morganfw** [Cacti/cacti#5904]
Hi,
after create a device and apply Apache Webserver template, in Graphs tab, 2 Graphs are blank and a '500 Internal Server Error' appear.

The 2 graphs are 'Apache HTTP - bytes/Hit'

![image](https://github.com/user-attachments/assets/c26af8ca-e7bd-46f1-a722-8e5e22e87e7f)

and 'Apache HTTP - Thread Detail %'

![image](https://github.com/user-attachments/assets/454766ce-739b-464c-967c-9906bfd7111b)

below the error written in cacti.log

```
2024-11-09 17:45:21 - PHP ERROR Backtrace: (CactiShutdownHandler())
--
2024-11-09 17:45:21 - ERROR PHP ERROR: Uncaught TypeError: generate_graph_best_cf(): Return value must be of type string, null returned in /var/www/html/cacti/lib/functions.php:3439 Stack trace: #0 /var/www/html/cacti/lib/rrd.php(1756): generate_graph_best_cf() #1 /var/www/html/cacti/graph_realtime.php(229): rrdtool_function_graph() #2 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 3439
2024-11-09 17:45:16 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-11-09 17:45:16 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-11-09 17:45:16 - ERROR PHP ERROR: Uncaught TypeError: generate_graph_best_cf(): Return value must be of type string, null returned in /var/www/html/cacti/lib/functions.php:3439 Stack trace: #0 /var/www/html/cacti/lib/rrd.php(1756): generate_graph_best_cf() #1 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #2 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 3439
2024-11-09 17:45:16 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-11-09 17:45:16 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-11-09 17:45:16 - ERROR PHP ERROR: Uncaught TypeError: generate_graph_best_cf(): Return value must be of type string, null returned in /var/www/html/cacti/lib/functions.php:3439 Stack trace: #0 /var/www/html/cacti/lib/rrd.php(1756): generate_graph_best_cf() #1 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #2 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 3439
```

**Comment by TheWitness** [comment]
Likely this is transient, but let me fix it.  Once the Graphs are all created, it should work find.

**Comment by TheWitness** [comment]
All fixed up now.  Keep breaking it!!!
