### ISSUE TITLE
[CACTI 1.2.x - latest branch and commits] PHP errors - fatal crash - Error:500

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/cacti#5925]
Hi @TheWitness ,

i have merged latest commits but we see now a lot of errors into cacti log:

```
2024-11-19 15:37:43 - CMDPHP ERROR: debounce key was truncated from debounce_page_error_thold_graph.php?headercontent=true to debounce_page_error_thold_graph.php?headercontent= Backtrace: (/help.php[43]:debounce_run_notification(), /lib/functions.php[7435]:cacti_debug_backtrace())
2024-11-19 15:37:43 - CMDPHP WARNING: Cacti Page:thold_graph.php?headercontent=true for User:xxxxxxx Generated a Fatal Error:500
2024-11-19 15:37:42 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2024-11-19 15:37:42 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024-11-19 15:37:42 - ERROR PHP ERROR in Plugin 'thold': Uncaught TypeError: Unsupported operand types: string * int in /var/www/html/cacti/plugins/thold/thold_graph.php:388 Stack trace: #0 /var/www/html/cacti/plugins/thold/thold_graph.php(56): tholds() #1 {main} thrown in file: /var/www/html/cacti/plugins/thold/thold_graph.php on line: 388
2024-11-19 15:37:34 - MAILER INFO: Mail successfully sent via SMTP from 'xxxxxx <xxx@xxxx>', to 'Administrator <xxxxx@xxxxx.it>', cc '', bcc '', and took 0.10 seconds, Subject 'Cacti System Warning'
2024-11-19 15:37:34 - CMDPHP ERROR: debounce key was truncated from debounce_page_error_thold_graph.php?headercontent=true to debounce_page_error_thold_graph.php?headercontent= Backtrace: (/help.php[43]:debounce_run_notification(), /lib/functions.php[7435]:cacti_debug_backtrace())
2024-11-19 15:37:34 - CMDPHP WARNING: Cacti Page:thold_graph.php?headercontent=true for User:xxxxxxx Generated a Fatal Error:500
2024-11-19 15:37:34 - MAILER INFO: Mail successfully sent via SMTP from 'xxxx <xxxx@xxx>', to 'Administrator <xxxxx@xxxxx.it>', cc '', bcc '', and took 0.14 seconds, Subject 'Cacti System Warning'
2024-11-19 15:37:34 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2024-11-19 15:37:34 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024-11-19 15:37:34 - ERROR PHP ERROR in Plugin 'thold': Uncaught TypeError: Unsupported operand types: string * int in /var/www/html/cacti/plugins/thold/thold_graph.php:388 Stack trace: #0 /var/www/html/cacti/plugins/thold/thold_graph.php(56): tholds() #1 {main} thrown in file: /var/www/html/cacti/plugins/thold/thold_graph.php on line: 388
2024-11-19 15:37:29 - CMDPHP WARNING: Cacti Page:syslog.php?headercontent=true for User:xxxxxxx Generated a Fatal Error:500
2024-11-19 15:37:29 - MAILER INFO: Mail successfully sent via SMTP from 'xxxx <xxx@xxx>', to 'Administrator <xxxxx@xxxxx.it>', cc '', bcc '', and took 0.10 seconds, Subject 'Cacti System Warning'
2024-11-19 15:37:29 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'syslog'
2024-11-19 15:37:29 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024-11-19 15:37:29 - ERROR PHP ERROR in Plugin 'syslog': Uncaught Error: Call to undefined function syslog_connect() in /var/www/html/cacti/plugins/syslog/syslog.php:38 Stack trace: #0 {main} thrown in file: /var/www/html/cacti/plugins/syslog/syslog.php on line: 38

2024-11-19 16:05:32 - CMDPHP ERROR: debounce key was truncated from debounce_page_error_reports_admin.php?headercontent=true to debounce_page_error_reports_admin.php?headerconten Backtrace: (/help.php[43]:debounce_run_notification(), /lib/functions.php[7435]:cacti_debug_backtrace())
2024-11-19 16:05:32 - CMDPHP WARNING: Cacti Page:reports_admin.php?headercontent=true for User:xxxxxxx Generated a Fatal Error:500
2024-11-19 16:05:32 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024-11-19 16:05:32 - ERROR PHP ERROR: Uncaught TypeError: Unsupported operand types: string * int in /var/www/html/cacti/lib/html_reports.php:1920 Stack trace: #0 /var/www/html/cacti/reports_admin.php(166): reports() #1 {main} thrown in file: /var/www/html/cacti/lib/html_reports.php on line: 1920
```

thanks a lot
stefano

**Comment by TheWitness** [comment]
What commit?  What branch?

**Comment by xmacan** [comment]
I have met this issue with monitor plugin too but with older cacti version... weird

**Comment by anarkia1976** [comment]
> What commit? What branch?

Hi, latest commits, branch 1.2.x, thanks a lot.

```
2024-11-21 08:24:34 - CMDPHP ERROR: debounce key was truncated from debounce_page_error_reports_admin.php?headercontent=true to debounce_page_error_reports_admin.php?headerconten Backtrace: (/help.php[43]:debounce_run_notification(), /lib/functions.php[7435]:cacti_debug_backtrace())
2024-11-21 08:24:33 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2024-11-21 08:24:33 - ERROR PHP ERROR: Uncaught TypeError: Unsupported operand types: string * int in /var/www/html/cacti/lib/html_reports.php:1920 Stack trace: #0 /var/www/html/cacti/reports_admin.php(166): reports() #1 {main} thrown in file: /var/www/html/cacti/lib/html_reports.php on line: 1920
```

PHP 8.1.2-1ubuntu2.19 (cli) (built: Sep 30 2024 16:25:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.19, Copyright (c), by Zend Technologies

mysql  Ver 15.1 Distrib 10.6.18-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by anarkia1976** [comment]
hello @TheWitness @xmacan, 

I ran further tests by discriminating the browsers.

I saw that with chrome and edge the cacti server worked correctly without problems.

Using the opera browser instead the cacti crashed with error 500, I solved the problem by running an advanced clear cache.

What I don't understand however is the fact that the application crashed completely, I would have expected a browser error only.

For now we can close the problem reported. thank you very much as always.

**Comment by TheWitness** [comment]
A 500 error is generally not a browser side issue, but I'm okay closing now too.  At SC24, so I've been a bit distracted this week.

**Comment by TheWitness** [comment]
@anarkia1976, I reopened this to address one of the error messages, this one:

```
CMDPHP ERROR: debounce key was truncated from debounce_page_error_thold_graph.php?headercontent=true to debounce_page_error_thold_graph.php?headercontent=
```

I've re-engineered the debounce to store this data differently in 1.3.0 in order to preserved the page as it was called, but prevent the key from being truncated.

Commit was here: 

https://github.com/Cacti/cacti/commit/1db3b3108095b4b7745a1276e0207e9091cfc7a3
