### ISSUE TITLE
Cacti  1.3.0 - Dev 803a3eac - Error 500 and several errors in log

### ISSUE THREAD

**Issue by morganfw** [Cacti/cacti#5944]
Hi, after latest git pull I got an Error 500 in Cacti GUI

![image](https://github.com/user-attachments/assets/7f365408-e4fe-48ba-9403-247d9cbeaec6)

```
git log
803a3eacc12bb192b2ac2bb646d3c5d316e31dbc (HEAD -> develop, origin/develop, origin/HEAD) QA: #5212 and #5196 - You need RRDtool 1.8++ for Gradients
[...]
```

below my compiled RRDtool version from latest git source:

```
/opt/rrdtool-1.9.x-patched/bin/rrdtool
RRDtool 1.9.0  Copyright by Tobias Oetiker <tobi@oetiker.ch>
               Compiled Nov 17 2024 10:51:17

Usage: rrdtool [options] command command_options
Valid commands: create, update, updatev, graph, graphv,  dump, restore,
                last, lastupdate, first, info, list, fetch, tune,
                resize, xport, flushcached

RRDtool is distributed under the Terms of the GNU General
Public License Version 2. (www.gnu.org/copyleft/gpl.html)

For more information read the RRD manpages
```

Below errors in cacti.log

```
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:24 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:24 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:24 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:24 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
2024-12-02 17:55:24 - CMDPHP WARNING: Cacti Page:graph_view.php for User:admin Generated a Fatal Error:500
2024-12-02 17:55:23 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:23 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:23 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:23 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
2024-12-02 17:55:23 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:23 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:23 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:23 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
2024-12-02 17:55:23 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:23 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:23 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:23 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
2024-12-02 17:55:23 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:23 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:23 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:23 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
2024-12-02 17:55:23 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:23 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:23 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:23 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
2024-12-02 17:55:23 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:23 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:23 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:23 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
2024-12-02 17:55:23 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:23 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:23 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:23 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
2024-12-02 17:55:23 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-02 17:55:23 - ERROR PHP ERROR: Uncaught TypeError: version_to_bits(): Argument #1 ($version) must be of type string, null given, called in /var/www/html/cacti/lib/functions.php on line 7309 and defined in /var/www/html/cacti/lib/functions.php:7467 Stack trace: #0 /var/www/html/cacti/lib/functions.php(7309): version_to_bits() #1 /var/www/html/cacti/lib/rrd.php(2411): cacti_version_compare() #2 /var/www/html/cacti/graph_json.php(168): rrdtool_function_graph() #3 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 7467
2024-12-02 17:55:23 - PHP ERROR WARNING Backtrace: (/graph_json.php[168]:rrdtool_function_graph(), /lib/rrd.php[2411]:CactiErrorHandler())
2024-12-02 17:55:23 - ERROR PHP WARNING: Undefined variable $rrdversion in file: /var/www/html/cacti/lib/rrd.php on line: 2411
```

**Comment by TheWitness** [comment]
It's fixed already.

**Comment by morganfw** [comment]
> It's fixed already. 

Yes I confirm that's fixed.

Thank you for support!

**Comment by TheWitness** [comment]
@morganfw, the pace of table changes will not slow, and once and a while, I'll make a commit that breaks things.  So, keep an eye open for bad behavior.  I'm trying to keep things running clean, but mistakes happen.

**Comment by TheWitness** [comment]
There are tons of balls in flight right now.  It's all good once the QA and bug reporting fill help fill my lack of fore thought.
