### ISSUE TITLE
[QA 1.3] - Cannot install plugin on fresh install of develop cacti.

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#5995]
**Describe the bug**

**To Reproduce**
try to install the plugin on a freh 

```
2024-12-14 01:43:56 - PHP ERROR Backtrace: (CactiShutdownHandler())
2024-12-14 01:43:56 - ERROR PHP ERROR: Uncaught Error: Call to undefined function , () in /var/www/html/cacti/lib/database.php:1864 Stack trace: #0 /var/www/html/cacti/plugins/reportit/system/install.php(374): db_table_create() Cacti/plugin_reportit#1 /var/www/html/cacti/plugins/reportit/setup.php(627): reportit_system_install() Cacti/plugin_reportit#2 /var/www/html/cacti/plugins/reportit/setup.php(44): reportit_system_setup() Cacti/plugin_reportit#3 /var/www/html/cacti/lib/plugins.php(763): plugin_reportit_install() Cacti/plugin_reportit#4 /var/www/html/cacti/plugins.php(229): api_plugin_install() Cacti/plugin_reportit#5 {main} thrown in file: /var/www/html/cacti/lib/database.php on line: 1864
```

**Comment by TheWitness** [comment]
Transferring this to a Cacti issue.  Just fixing this morning.
