### ISSUE TITLE
[probably not a bug] - upgrade_database error

### ISSUE THREAD

**Issue by dallenk** [Cacti/cacti#6023]
Keep in mind I just did a upgrade from an old develop to 7c0ea58d2 and ran the database upgrade, but seeing this error.   upgraded php to 8.1 as well. 

Anything quick for me to look at, or did I bork it by waiting too long and upgraded too far of a jump?

```
sudo -u www-data php cli/upgrade_database.php --forcever=1.2.29
NOTE: Repairing Tables for Local Database
Upgrading from v1.2.29
Performing Database Upgrade
  - from v1.2.29 (DB 1.3.0)
      to v1.3.0
++++++++++++++++++++++++++++++++++++++++++++++PHP Fatal error:  Uncaught Error: Call to undefined function rmdir_recursive() in /var/www/cacti/install/functions.php:312
Stack trace:
#0 /var/www/cacti/install/functions.php(180): install_rmdir_recursive()
#1 /var/www/cacti/install/upgrades/1_3_0.php(367): prune_deprecated_files()
#2 /var/www/cacti/cli/upgrade_database.php(149): upgrade_to_1_3_0()
#3 {main}
  thrown in /var/www/cacti/install/functions.php on line 312
```

7c0ea58d2 (HEAD -> develop, origin/develop, origin/HEAD) QA: The spacer is showing on the main collector edit

**Comment by dallenk** [comment]
yea. I think I borked it lol.  45 mins here now after trying a couple things..
![image](https://github.com/user-attachments/assets/eb8c791b-b7e3-4698-b095-bc38b3027852)


looks like I'm recreating this one :)
